# choose starting image @ node:latest
FROM node

MAINTAINER Alin CHIS <alin.d.chis@gmail.com>


# RUN apt-get update && apt-get install -y texlive

# add npm packages
RUN npm install --global --unsafe --silent \
  pg \
  pg-hstore \
  knex

# more stuff...

# environment variables


# add symlinks


# start command
