version: "3"

services:

  control-server:
    build: "../docker-containers/control-server"
    image: alinchis/control-server
    volumes:
      - "../control-server:/root/patj-manager/control-server"
      - "../docker-data/control:/root/patj-manager/control-data"
    working_dir: /root/patj-manager/control-server
    command: bash -c "npm install && npm run dev"
    depends_on:
      - "pgsql-server"
    ports:
      - "3333:3030"

  pgsql-server:
    env_file:
      - .env
    build: "../docker-containers/pgsql-server"
    image: alinchis/pgsql-server
    restart: always
    volumes:
      - "../docker-data/postgresql:/var/lib/postgresql"
    ports:
      - "5555:5432"
