version: "3"

services:

  control-server:
    build: "../docker-containers/control-server"
    image: alinchis/control-server
    volumes:
      - "../control-server:/root/patj-manager/control-server"
      - "../docker-data/control:/root/patj-manager/control-data"
    working_dir: /root/patj-manager/control-server
    command: bash -c "npm install && sequelize db:migrate && npm start"
    depends_on:
      - "pgsql-server"
    ports:
      - "3333:3030"

  display-server:
    build: "../docker-containers/display-server"
    image: alinchis/display-server
    volumes:
      - "../display-server:/root/patj-manager/display-server"
    working_dir: /root/patj-manager/display-server
    command: bash -c "npm install && npm run serve"
    ports:
      - "8001:8080"
    depends_on:
      - "control-server"

  latex-server:
    build: "../docker-containers/latex-server"
    image: alinchis/latex-server
    volumes:
      - "../latex-server:/root/patj-manager/latex-server"
    working_dir: /root/patj-manager/latex-server
    command: bash -c "npm install && npm start"
    depends_on:
      - "control-server"
    ports:
      - "4444:4040"

  pgsql-server:
    build: "../docker-containers/pgsql-server"
    image: alinchis/pgsql-server
    restart: always
    volumes:
      - "../docker-data/postgresql:/var/lib/postgresql"
    ports:
      - "5555:5432"
