# choose starting image @ fermiumlabs/latex-docker
FROM fermiumlabs/latex-docker

MAINTAINER Alin CHIS <alin.d.chis@gmail.com>

# RUN apt-get update && apt-get install -y texlive

# add npm packages
# RUN npm install --global --unsafe --silent \
#   body-parser \
#   cookie-parser \
#   debug \
#   express \
#   morgan \
#   pug \
#   serve-favicon \
  # pg \
  # pg-hstore \
#   babel-cli \
#   node-latex \
#   nodemon \
#   fs \
  # sequelize \
  # sequelize-cli

# more stuff...

# environment variables


# add symlinks


# start command
