# choose starting image @ node:latest
FROM node

LABEL maintainer="alin.d.chis@gmail.com"

# add vue-cli
RUN npm install --global --silent \
  @vue/cli

# more stuff...
EXPOSE 8080

# environment variables


# add symlinks


# start command
