# choose starting postgres:latest
FROM kartoza/postgis

MAINTAINER Alin CHIS <alin.d.chis@gmail.com>

# more stuff...

# environment variables
ENV POSTGRES_PASSWORD="mysecretpassword"
ENV POSTGRES_USER="thor"
ENV POSTGRES_DB="patj"
# add symlinks


# start command
